### ISSUE TITLE
Better error message with missing pak files

### ISSUE THREAD

**Issue by matthewearl** [j0zzz/JoeQuake#86] opened 2023-01-23 07:18 UTC
Currently get the "couldn't load gfx.wad" message, which is rather cryptic for a newbie. Maybe something like "could not find pak0.pak. This file should be copied in from a retail Quake installation (eg. Steam / GoG / CD-ROM). See the installation guide at https://speeddemosarchive.com/quake/guide.html"?

**Comment by Flecked42** [comment] 2023-01-26 19:11
Not a bad idea, i think having the error point to a install txt included with JoeQuake may be a better way.

**Comment by j0zzz** [comment] 2023-01-26 20:48
What's the exact use case to get this error? If I remove the pak files from id1 directory the first error I get is 
"Couldn't load gfx/palette.lmp". How on earth do they pass this file? Is there some kind of altered pak0.pak they use?

**Comment by matthewearl** [comment] 2023-01-26 21:18
I get the gfx.wad error if I put joequake-gl.exe in an empty directory and then run it.

**Comment by j0zzz** [comment] 2023-01-26 21:26
Thanks Matt. I had an extracted gfx.wad in my joequake folder, who would've thought :)
Should've tried to reproduce the exact use case. My bad.

**Comment by j0zzz** [comment] 2023-01-28 22:04
I came up with this dialog. What do you think?
Pressing yes opens the default browser with the url.
![image](https://user-images.githubusercontent.com/57400093/215293080-f8d0312b-56eb-445c-ae71-99bf2c909ff4.png)

**Comment by matthewearl** [comment] 2023-01-28 22:46
That error message looks good to me although after checking it seems that "GOG" is the right capitalization. Browser opening is a good idea too. I agree that the dzip Sys_Error is unnecessary here --- I don't think I thought about this case. It should definitely not be shown if we crash out before we tried to initialise it.

**Comment by Flecked42** [comment] 2023-01-29 03:08
Should probably say Quake pak files (pak0.pak, pak1.pak) since you need both.

**Comment by j0zzz** [comment] 2023-01-29 15:56
Fixed in commit 30b42b4

**Closed by j0zzz** 2023-01-29 15:56 UTC
