### ISSUE TITLE
Level loading time is added onto game start time (up to 0.1 seconds)

### ISSUE THREAD

**Issue by matthewearl** [j0zzz/JoeQuake#128] opened 2023-08-29 07:56 UTC
If a map takes less than 0.1 seconds to load, then that load time is added onto the time that the player gets control.   I have noticed this "in the wild" but I've also put together a branch for easy reproduction of the issue [here](https://github.com/j0zzz/JoeQuake/compare/master...matthewearl:JoeQuake-1:load-delay-repro?expand=1).

Repro steps:

1. Build with the above branch https://github.com/matthewearl/JoeQuake-1/tree/load-delay-repro
2. Record a demo on 100m just holding forwards.
3. Set the above demo as ghost.
4. Play 100m with various settings of `sv_loaddelay`.

Here's what you should see:

`sv_loaddelay 0`:
![joequake017](https://github.com/j0zzz/JoeQuake/assets/1709642/ecf959ae-2ce2-4470-911c-9e018ac9fdd3)
(ghost split +0.01)

`sv_loaddelay 0.05`:
![joequake019](https://github.com/j0zzz/JoeQuake/assets/1709642/d4a2855b-25bb-4496-bf9a-8faef167b21f)
(ghost split +0.05)

`sv_loaddelay 0.09`:
![joequake020](https://github.com/j0zzz/JoeQuake/assets/1709642/9ad9251d-0a94-46f1-8143-2204d892df00)
(ghost split +0.09)

`sv_loaddelay 0.11`:
![joequake021](https://github.com/j0zzz/JoeQuake/assets/1709642/0638d101-5eea-4257-9900-8edb9f1ecc0d)
(ghost split +0.01)

I noticed this first when playing `fmb_bdg2` a normal branch.  It turned out that I had recorded my ghost in a release build, but was playing it in a debug build, which pushed the load time over 0.1 seconds, so I had a 0.1 second advantage relative to the ghost.

**Comment by j0zzz** [comment] 2023-08-29 12:45
Did this work differently in the vanilla Win/GLQuake?

> but was playing it in a debug build, which pushed the load time over 0.1 seconds

So does this only occur in a debug build?

**Comment by matthewearl** [comment] 2023-08-29 16:06
> So does this only occur in a debug build?

It doesn't only occur in debug mode, it's just that I happened to see it when switching between debug and release since debug mode put me over  the 0.1 second boundary and release slightly under, on the `fmb_bdg2` map (large enough that it takes approx 0.1 seconds to load on a modern machine).

> Did this work differently in the vanilla Win/GLQuake?

I just tested this with [quakegeneric](https://github.com/erysdren/quakegeneric) which is the closest thing to original source I can get that builds easily.   It does in fact have a similar effect, although slightly different.  The behaviour is the same for load times less than 0.1 seconds --- in these cases the start time is delayed by the same amount as the load time.  For load times greater than 0.1 second, the original source delays the start by 0.1 seconds, whereas JQ eliminates the delay so you're technically at an advantage in JQ if you have a slower load.

Having said this, since a very similar feature is present in the original source, I guess we don't care too much about it?

**Comment by matthewearl** [comment] 2023-08-29 16:07
FWIW I just tried with `cl_independentphysics 0` and it behaves identically to quakegeneric (delays by 0.1 seconds for a load time > 0.1 second)

**Comment by Flecked42** [comment] 2023-08-29 18:23
![Screenshot (65)](https://github.com/j0zzz/JoeQuake/assets/90434262/91b77591-a5b9-4a74-8273-27b6141d3b73)

Our check tool flagged your fmb2_113 demo for the start time.

**Comment by j0zzz** [comment] 2023-08-29 18:30
Yeah this definately needs to be addressed.

**Comment by matthewearl** [comment] 2023-08-29 18:47
It would be good if you can check it works on windows.  Putting a 0.2 second sleep in `SV_SpawnServer`, recording a 100m demo, then running the check tool should be enough to confirm it

**Comment by matthewearl** [comment] 2023-08-29 18:51
I also see it just recording a demo on `ad_sepulcher` without any modification, since that takes > 0.1 seconds to load in any case.

**Comment by j0zzz** [comment] 2023-08-30 18:25
Great findings, thanks Matt!

**Comment by j0zzz** [comment] 2023-08-31 20:30
Now that I actually had some time to understand what's going on, I came up with this (easiest?) fix:

`	minphysframetime = MinPhysFrameTime();
	if (cls.capturedemo || cls.timedemo || realtime - oldphysrealtime >= minphysframetime)
	{
		physframetime = realtime - oldphysrealtime;
		oldphysrealtime = realtime;
	
		// joe: never allow physframetime to go above 0.1
		// this guarantees that after a longer map load (> 0.1s), a physical server frame is executed immediately
		physframetime = min(physframetime, 0.1);
	}`

So if we clamp physframetime at max 0.1, just as we do with host_frametime, the condition
`if (extraphysframetime < physframetime)`
wouldn't be true and therefore we could force out the proper physical frame to be performed.
I believe there isn't any danger with this, as with normal circumstances the server can never run smaller than 10 fps (0.1 frametime) anyways.
Tested on many long-loading AD maps, none of them resulted the early 1.318888 start time with the fix.

Matt, what do you think?

**Comment by matthewearl** [comment] 2023-09-01 09:17
I think that addresses the issue as described in my post, but I'm still seeing the 1.31888 initial time with a different setup, and slightly intermittently:

1. Set `cl_maxfps 500` (exact value probably not important).
2. Bind `record 100m 100m` to something.
3. Hit the bind.

Most of the time I end up with the 1.31888 initial time start time.  If you use my load-delay-repro repro branch you can see the issue occurs without having to check the demo:  Just hit the bind until the line `thinking 1.327778` appears on the console, then `stop`, check the demo, and it should have an initial time of 1.31888.  Make sure you have `sv_loaddelay 0`.

This seems to occur when `Host_FilterTime` updates `host_frametime` but does not update `physframetime`, which is likely to happen since `host_frametime` ticks at 500 fps, and `physframetime` ticks at 72fps.  As long as the level load time falls somewhere between 1/500 seconds and 1/72 seconds this can happen.

When `host_frametime` is updated, it is updated to whatever the level load time is, however, `physframetime` remains at 0.1: the value which was set in `SV_SpawnServer`. In this case the `if (extraphysframetime < physframetime)` check will pass and we won't run a physics frame.

If you can repro this too that'd be good to know, just in case I've made a mistake.

**Comment by j0zzz** [comment] 2023-09-01 09:35
> When `host_frametime` is updated, it is updated to whatever the level load time is, however, `physframetime` remains at 0.1

As far I see `host_frametime` is always clamped to 0.1

![image](https://github.com/j0zzz/JoeQuake/assets/57400093/8275e5c1-1c21-4a59-b878-c4cac4dceaa8)

And exactly the opposite, `physframetime` was that could go beyond 0.1 due to the bug. With the fix it remains at 0.1 max.
I tried to reproduce it with the steps you described, but now the start times are always 1.3999999 to me.

**Comment by matthewearl** [comment] 2023-09-01 09:58
Do you have a delay in `SV_SpawnServer`?  For the new issue I'm seeing there should be no delay

**Comment by j0zzz** [comment] 2023-09-01 10:42
Ok, I could reproduce it with a release build, not with a previously built debug build. 
This experience popped the idea out of my head that it's simply that fast with today's computers. So I started my good old GLQuake.exe (v0.96) and repeated the steps. Guess what? Yeah, you guessed right.
![image](https://github.com/j0zzz/JoeQuake/assets/57400093/a31d5e8f-806f-4038-98d1-ce958de7376d)

**Comment by matthewearl** [comment] 2023-09-01 10:51
Are both of those recorded with the old glquake exe?  Seems weird you're getting times less than 1.31888

**Comment by j0zzz** [comment] 2023-09-01 11:08
Fixed in commit 8130554
Thanks for the help @matthewearl

**Closed** 2023-09-01 11:09 UTC
Labels: bug, help wanted

**Comment by matthewearl** [comment] 2023-09-01 11:11
Oh, my mistake, I forgot what 1./72 was :sweat_smile:.   Yeah what GLQuake is doing makes perfect sense.   But still,  there seems to be a difference with JQ in that it's possible to get an initial time of *exactly* `1.3+1/72=1.3138888`, whereas with GLQuake I don't think that is possible?

**Comment by j0zzz** [comment] 2023-09-01 11:15
Well I haven't tested thoroughly. I believe it should be possible with GLQuake too, at least when I implemented independent physics, I payed very high attention to not break anything but keep the server side fps calculation 100% accurate.

**Comment by j0zzz** [comment] 2023-09-01 11:27
Just recorded this:
![image](https://github.com/j0zzz/JoeQuake/assets/57400093/5afa7bb0-c2ac-4f66-8ab4-fb06c4abe018)

**Comment by matthewearl** [comment] 2023-09-01 11:36
I think you're right, thanks for indulging me :)
